using UnityEngine;

namespace Groop.Plants
{
    /// <summary>
    /// Represents a plant that can be placed in the game world.
    /// This class is used to define the properties of a plant that can be instantiated in the game.
    /// </summary>

    [CreateAssetMenu(fileName = "PlacablePlant", menuName = "Groop/PlacablePlant")]
    public class PlacablePlant : ScriptableObject
    {
        /// <summary>
        ///   Gets or sets the prefab of the seed that will be instantiated when the plant is placed in the world.
        /// </summary>
        [field: SerializeField]
        public GameObject SeedPrefab { get; private set; }

        /// <summary>
        ///    Gets or sets the prefab of the plant that will be instantiated when the seed grows into a plant.
        /// </summary>
        [field: SerializeField]
        public GameObject PlantPrefab { get; private set; }

        /// <summary>
        ///     Gets or sets the time in milliseconds it takes for the seed to grow into the first stage of the plant. 
        /// </summary>
        [field: SerializeField]
        public int SeedGrowTime { get; private set; }

        /// <summary>
        ///     Gets or sets the time in milliseconds it takes for the plant to grow to its full size.
        /// </summary>
        [field: SerializeField]
        public int PlantGrowTime { get; private set; }

        /// <summary>
        ///     Gets or sets the cost of the plant in the game currency.
        /// </summary>
        [field: SerializeField]
        public int Cost { get; private set; }

        /// <summary>
        ///     Gets or sets the profit generated by the plant when harvested.
        /// </summary>
        [field: SerializeField]
        public int Profit { get; private set; }
    }
}